"""add user phone

Revision ID: 07239bf8c907
Revises: 7bce8d41949e
Create Date: 2022-05-21 08:52:10.500358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07239bf8c907'
down_revision = '7bce8d41949e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
